apiVersion: v1
kind: Service
metadata:
  name: test01
  namespace: namespace-workflow-1720813733287
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test01
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000